name: 'Setup JDK'
description: >
  This action sets up JDK 17 for Java projects.
  It is used to ensure that the Java environment is ready for building and testing Java applications.

inputs:
  java-distribution: { description: 'Java distribution to use (e.g., temurin)', required: false, default: 'temurin' }
  java-version: { description: 'Java version to use (e.g., 17)', required: false, default: '17' }

runs:
  using: composite
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.java-distribution }}  
        java-version: ${{ inputs.java-version }}


