name: Tagged Version Java Library Workflow
description: > 
  This is the workflow for a tagged version of a Java library.

on: 
  workflow_call:
    inputs:
      jf-url:
        description: 'JFrog URL'
        required: true
        type: string
      jf-repo-resolve-releases:
        description: 'Repository for resolving releases'
        required: false
        default: 'maven'
        type: string
      jf-repo-resolve-snapshots:
        description: 'Repository for resolving snapshots'
        required: false
        default: 'maven'
        type: string
      jf-upload-repo-path:
        description: 'Path of the JFrog repository where the artifact will be uploaded'
        required: true
        type: string
      java-distribution:
        description: 'Java distribution to use (e.g., temurin)'
        required: false
        default: 'temurin'
        type: string
      java-version: 
        description: 'Java version to use (e.g., 17)'
        required: false
        default: '17'
        type: string
    secrets:
      jf-access-token:
        description: 'JFrog Access Token'
        required: true


jobs:
  main-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: diego4bits/reusable-workflow-components/.github/actions/setup-jdk@main
        with:
          java-distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}

      - name: Setup JFrog CLI - Auth Token
        uses: diego4bits/reusable-workflow-components/.github/actions/setup-and-config-jfrog@main
        with:
          jf-url: ${{ inputs.jf-url }}
          jf-access-token: ${{ secrets.jf-access-token }}
          jf-repo-resolve-releases: ${{ inputs.jf-repo-resolve-releases }}
          jf-repo-resolve-snapshots: ${{ inputs.jf-repo-resolve-snapshots }}

      - name: Build & Test Using Maven & JFrog
        id: build-and-test-mvn
        uses: diego4bits/reusable-workflow-components/.github/actions/build-and-test-mvn@main

      - name: Upload JAR & POM to JFrog
        uses: diego4bits/reusable-workflow-components/.github/actions/upload-to-jfrog-jar-pom@main
        with:
          jar-path: ${{ steps.build-and-test-mvn.outputs.jar-path }}
          pom-path: ${{ steps.build-and-test-mvn.outputs.pom-path }}
          jf-upload-repo-path: ${{ inputs.jf-upload-repo-path }}/${{ github.ref_name }}/
